name: "Cross Commit"
description: "Cross Commits Files from the base repository to another repo"
inputs:
  source-folder:
    description: "Sub folder of the repository to copy"
    required: true
  destination-repository:
    description: "Repository to be commited to. In case of private repository, state with access token as a secret"
    required: true
  destination-folder:
    description: "Sub folder of the repository to copy into"
    required: true
  destination-branch:
    description: "Branch of the destination repository to commit to"
    required: true
    default: "alpha"
  git-user:
    description: "User that will be used to create the git commit"
    required: true
  git-user-email:
    description: "User email that will be used to create the git commit"
    required: true
  git-commit-message:
    description: "Custom commit message to use"
    default: ""
    required: false
  excludes:
    description: "Optionally exclude some directories from being synced in both src and dst. The value is treated as column separated list, e.g. skip_dir_in_src:.git:skip_dir_in_dst"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source-folder }}
    - ${{ inputs.destination-repository }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.destination-branch }}
    - ${{ inputs.git-user }}
    - ${{ inputs.git-user-email }}
    - ${{ inputs.excludes }}
